version: '3'

services:
  customer-service:
    image: postgres:latest
    container_name: company-service
    environment:
      POSTGRES_DB: company
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - company-network

networks:
  company-network:
    driver: bridge
